name: Release

on:
  release:
    types: [published]        # fires for both prerelease and full release

permissions:
  contents: read              # checkout
  id-token: write             # REQUIRED for Trusted Publishing (OIDC)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the release tag
        uses: actions/checkout@v4
        with:
          # build exactly what was tagged for the release
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools wheel twine packaging
          python -m build
          ls -l dist

      - name: Twine check (sanity)
        run: |
          python -m pip install --upgrade twine
          twine check dist/*

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/*

  # Publish prereleases to TestPyPI
  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease }}   # only when Release is marked "prerelease"
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          verify-metadata: true
          skip-existing: true
          verbose: true

  # Publish full releases to PyPI
  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}  # only when Release is a full release
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verify-metadata: true
          skip-existing: true
          verbose: true